# Required to run your project under the correct environment.
language: php
dist: trusty

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
      env: CODECLIMATE=yes
    - php: 5.6
    - php: 7.0
    - php: hhvm
    - php: nightly


# Commands to be run before your environment runs.
install:
  - composer install --dev --no-interaction
  - phpenv rehash

# Commands you want to run that will verify your build.
script:
  - ./vendor/bin/phpunit -c tests/phpunit.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src ./tests ./example -n
  - ./vendor/bin/phpcpd ./src ./tests ./example -n
  - >
    if [[ "$CODECLIMATE" == "yes" ]]; then
      composer require codeclimate/php-test-reporter:dev-master --dev --no-interaction
      CODECLIMATE_REPO_TOKEN=a84b61ed5cca760894732b4b9e61dc15d584c89abd4c696dc78ca78e429b1207 ./vendor/bin/test-reporter
    fi
